# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Project FiFo Cloud Orchestration
version: 0.8.2
version_name: Cautious Collie
email: sales@project-fifo.net
description: > # this means to ignore newlines until "baseurl:"
  Project FiFo cloud orchestration
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://project-fifo.net" # the base hostname & protocol for your site
twitter_username: project_fifo
github_username:  project_fifo

# Build settings
markdown: kramdown
